"""Add name field to Farm model

Revision ID: 8c5a99077d14
Revises: 857063f0b8da
Create Date: 2025-04-26 12:34:24.307822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5a99077d14'
down_revision = '857063f0b8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
